name: CD for dev docs (fw & web)

on:
  push:
    branches:
    - 'main'
    - 'feature-fw/**'
    - 'feature-web/**'
    - 'doc/**'
    - 'infra/**'

jobs:
  # Generate Doxygen doc for FW api
  build-fw-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src_fw/platform-io

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Doxygen
      run: sudo apt install -y doxygen
    - name: Generate FW api document
      run: doxygen
    - name: Upload generated docs
      uses: actions/upload-artifact@v4
      with:
        name: build-fw-api
        path: src_fw/platform-io/docs/html/
        retention-days: 1


  # Generate Deno doc for WebApp api
  build-webapp-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src_web

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x
    - name: Generate WebApp api document
      run: |
        deno doc --html --name="Web DMX" --private static/*/*.js
        cp -f docs/all_symbols.html docs/index.html
    - name: Upload generated docs
      uses: actions/upload-artifact@v4
      with:
        name: modules-doc
        path: src_web/docs/
        retention-days: 1
