name: CI for code (fw)

on:
  push:
    branches:
    - 'main'
    - 'feature-fw/**'
    - 'infra/**'

jobs:
  # Build check of PlatformIO project
  c-pio-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src_fw/platform-io

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Restore PlatformIO download caches
      uses: actions/cache@v4
      id: platformio-restore
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: pio-build-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
    - name: Set up PlatformIO
      run: pip install --upgrade platformio
    - name: Run PlatformIO build
      run: pio run -e nucleo_f303k8
